# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-16 10:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20160112_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
