# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-20 08:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0007_developer_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('type', models.IntegerField(default=0)),
                ('category', models.IntegerField(default=0)),
                ('frozen', models.BooleanField(default=False)),
                ('vegetarian', models.BooleanField(default=False)),
                ('salty', models.BooleanField(default=False)),
                ('sweet', models.BooleanField(default=False)),
                ('description', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Developer',
        ),
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
