# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-18 10:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20160401_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dishes', to=settings.AUTH_USER_MODEL),
        ),
    ]
